import {
  User,
  Department,
  Branch,
  Employee,
  AttendanceRecord,
  LeaveRequest,
  Payslip,
  JobOpening,
  Candidate,
  PerformanceReview,
  Customer,
  Lead,
  Quotation,
  Invoice,
  Product,
  Warehouse,
  Supplier,
  PurchaseOrder,
  ExpenseClaim,
  Account,
  Project,
  Task,
  DocumentRecord,
  CalendarEvent,
  Asset,
  Ticket,
  Announcement,
  NotificationItem,
  AuditLog,
  CompanySettings,
  VisitorSession,
} from '../types';

export const initialCompanySettings: CompanySettings = {
  companyName: 'Nexora Business Solutions (Pvt.) Ltd.',
  registrationNumber: 'SECP-CORP-0189283-PK',
  taxNumber: 'NTN: 7492819-3 / STRN: 3277876123456 (FBR Active)',
  email: 'info@nexora.pk',
  phone: '+92 (21) 3587-9921',
  website: 'https://nexora.pk',
  address: 'Level 14, Executive Tower, Dolmen City, Clifton Block 4, Karachi, Pakistan',
  currency: 'PKR',
  currencySymbol: 'Rs.',
  timeZone: 'Asia/Karachi (PKT, UTC+5)',
  fiscalYearStart: 'July 1',
  workingDaysPerWeek: 5,
  standardWorkHoursPerDay: 8,
  autoBackup: true,
  twoFactorRequired: true,
};

export const initialBranches: Branch[] = [
  {
    id: 'br-1',
    name: 'Karachi Corporate Head Office',
    code: 'HQ-KHI',
    manager: 'Muhammad Hamza Khan',
    address: 'Dolmen Executive Tower, Clifton Block 4, Karachi',
    phone: '+92 (21) 3587-9921',
    email: 'karachi.hq@nexora.pk',
    status: 'Active',
  },
  {
    id: 'br-2',
    name: 'Lahore Tech & Operations Hub',
    code: 'HUB-LHE',
    manager: 'Ayesha Siddiqui',
    address: 'MM Alam Road, Gulberg III, Lahore',
    phone: '+92 (42) 3578-1122',
    email: 'lahore.hub@nexora.pk',
    status: 'Active',
  },
  {
    id: 'br-3',
    name: 'Islamabad Regional Center',
    code: 'REG-ISB',
    manager: 'Bilal Ahmed',
    address: 'Saudi Pak Tower, Jinnah Avenue, Blue Area, Islamabad',
    phone: '+92 (51) 280-4491',
    email: 'islamabad@nexora.pk',
    status: 'Active',
  },
];

export const initialDepartments: Department[] = [
  { id: 'dept-1', name: 'Executive & Governance', code: 'EXEC', managerId: 'usr-1', managerName: 'Muhammad Hamza Khan', employeeCount: 5, budget: 15000000 },
  { id: 'dept-2', name: 'Human Resources & EOBI', code: 'HR', managerId: 'usr-3', managerName: 'Fatima Tariq', employeeCount: 9, budget: 8500000 },
  { id: 'dept-3', name: 'Finance & FBR Tax Compliance', code: 'FIN', managerId: 'usr-4', managerName: 'Bilal Ahmed', employeeCount: 8, budget: 12000000 },
  { id: 'dept-4', name: 'Corporate Sales & BD', code: 'SALES', managerId: 'usr-8', managerName: 'Sana Mir', employeeCount: 16, budget: 18500000 },
  { id: 'dept-5', name: 'Software Engineering & IT', code: 'TECH', managerId: 'usr-5', managerName: 'Zain Ul Abideen', employeeCount: 28, budget: 35000000 },
  { id: 'dept-6', name: 'Supply Chain & Multi-Godown', code: 'SCM', managerId: 'usr-9', managerName: 'Tariq Mahmood', employeeCount: 14, budget: 14000000 },
  { id: 'dept-7', name: 'Customer Care & 24/7 SLA', code: 'SUPPORT', managerId: 'usr-6', managerName: 'Saad Farooq', employeeCount: 12, budget: 6500000 },
];

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    name: 'Muhammad Hamza Khan',
    email: 'admin@nexora.pk',
    role: 'Super Admin',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200',
    departmentId: 'dept-1',
    branchId: 'br-1',
    jobTitle: 'Managing Director & CEO',
    employeeId: 'NEX-001',
    phone: '+92 300 8291001',
    status: 'Active',
    twoFactorEnabled: true,
    lastLogin: 'Today, 08:30 AM',
  },
  {
    id: 'usr-2',
    name: 'Ayesha Siddiqui',
    email: 'ayesha@nexora.pk',
    role: 'Company Admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    departmentId: 'dept-1',
    branchId: 'br-2',
    jobTitle: 'Chief Operating Officer',
    employeeId: 'NEX-002',
    phone: '+92 301 8291002',
    status: 'Active',
    twoFactorEnabled: true,
    lastLogin: 'Today, 09:15 AM',
  },
  {
    id: 'usr-3',
    name: 'Fatima Tariq',
    email: 'fatima.hr@nexora.pk',
    role: 'HR Manager',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=200',
    departmentId: 'dept-2',
    branchId: 'br-1',
    jobTitle: 'Head of People & EOBI Compliance',
    employeeId: 'NEX-003',
    phone: '+92 302 8291003',
    status: 'Active',
    twoFactorEnabled: false,
    lastLogin: 'Today, 08:45 AM',
  },
  {
    id: 'usr-4',
    name: 'Bilal Ahmed',
    email: 'bilal.fin@nexora.pk',
    role: 'Finance Manager',
    avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&q=80&w=200',
    departmentId: 'dept-3',
    branchId: 'br-1',
    jobTitle: 'Chief Financial Officer (FCA / ICAP)',
    employeeId: 'NEX-004',
    phone: '+92 303 8291004',
    status: 'Active',
    twoFactorEnabled: true,
    lastLogin: 'Yesterday, 05:20 PM',
  },
  {
    id: 'usr-5',
    name: 'Zain Ul Abideen',
    email: 'zain.tech@nexora.pk',
    role: 'Department Manager',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    departmentId: 'dept-5',
    branchId: 'br-2',
    jobTitle: 'VP of Technology & Cloud Infrastructure',
    employeeId: 'NEX-005',
    phone: '+92 304 8291005',
    status: 'Active',
    twoFactorEnabled: false,
    lastLogin: 'Today, 10:02 AM',
  },
  {
    id: 'usr-6',
    name: 'Saad Farooq',
    email: 'saad.dev@nexora.pk',
    role: 'Employee',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200',
    departmentId: 'dept-5',
    branchId: 'br-1',
    jobTitle: 'Senior Full Stack Engineer',
    employeeId: 'NEX-012',
    phone: '+92 305 8291012',
    status: 'Active',
    twoFactorEnabled: false,
    lastLogin: 'Today, 08:55 AM',
  },
  {
    id: 'usr-7',
    name: 'Mariam Baig',
    email: 'mariam.acc@nexora.pk',
    role: 'Accountant',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    departmentId: 'dept-3',
    branchId: 'br-1',
    jobTitle: 'Senior FBR Tax & Accounts Specialist',
    employeeId: 'NEX-008',
    phone: '+92 306 8291008',
    status: 'Active',
    twoFactorEnabled: false,
    lastLogin: 'Today, 09:30 AM',
  },
  {
    id: 'usr-8',
    name: 'Sana Mir',
    email: 'sana.sales@nexora.pk',
    role: 'Sales Manager',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=200',
    departmentId: 'dept-4',
    branchId: 'br-1',
    jobTitle: 'Director of Enterprise B2B Sales',
    employeeId: 'NEX-007',
    phone: '+92 307 8291007',
    status: 'Active',
    twoFactorEnabled: false,
    lastLogin: 'Today, 07:45 AM',
  },
  {
    id: 'usr-9',
    name: 'Tariq Mahmood',
    email: 'tariq.inv@nexora.pk',
    role: 'Inventory Manager',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    departmentId: 'dept-6',
    branchId: 'br-1',
    jobTitle: 'General Manager Warehousing & Godowns',
    employeeId: 'NEX-010',
    phone: '+92 308 8291010',
    status: 'Active',
    twoFactorEnabled: false,
    lastLogin: 'Today, 08:10 AM',
  },
];

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    employeeId: 'NEX-001',
    firstName: 'Muhammad Hamza',
    lastName: 'Khan',
    email: 'admin@nexora.pk',
    phone: '+92 300 8291001',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200',
    department: 'Executive & Governance',
    jobTitle: 'Managing Director & CEO',
    role: 'Super Admin',
    manager: 'Board of Directors',
    branch: 'Karachi Corporate Head Office',
    joiningDate: '2020-01-15',
    status: 'Active',
    basicSalary: 650000,
    bankName: 'Meezan Bank Ltd (Islamic Banking)',
    accountNumber: 'PK92MEZN00010203040506',
    emergencyContact: { name: 'Zahra Khan', relationship: 'Spouse', phone: '+92 321 9912001' },
    skills: ['Corporate Governance', 'P&L Strategy', 'FBR Tax Strategy', 'Enterprise SaaS'],
  },
  {
    id: 'emp-2',
    employeeId: 'NEX-002',
    firstName: 'Ayesha',
    lastName: 'Siddiqui',
    email: 'ayesha@nexora.pk',
    phone: '+92 301 8291002',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    department: 'Executive & Governance',
    jobTitle: 'Chief Operating Officer',
    role: 'Company Admin',
    manager: 'Muhammad Hamza Khan',
    branch: 'Lahore Tech & Operations Hub',
    joiningDate: '2020-03-01',
    status: 'Active',
    basicSalary: 520000,
    bankName: 'Habib Bank Limited (HBL)',
    accountNumber: 'PK81HABB00192837465501',
    emergencyContact: { name: 'Dr. Tariq Siddiqui', relationship: 'Father', phone: '+92 333 4455667' },
    skills: ['Operations Scaling', 'Multi-City Branch Ops', 'Procurement Audit'],
  },
  {
    id: 'emp-3',
    employeeId: 'NEX-003',
    firstName: 'Fatima',
    lastName: 'Tariq',
    email: 'fatima.hr@nexora.pk',
    phone: '+92 302 8291003',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=200',
    department: 'Human Resources & EOBI',
    jobTitle: 'Head of People & EOBI Compliance',
    role: 'HR Manager',
    manager: 'Muhammad Hamza Khan',
    branch: 'Karachi Corporate Head Office',
    joiningDate: '2021-02-10',
    status: 'Active',
    basicSalary: 380000,
    bankName: 'Bank Alfalah Limited',
    accountNumber: 'PK45ALFH00992817263544',
    emergencyContact: { name: 'Noman Tariq', relationship: 'Brother', phone: '+92 345 8899001' },
    skills: ['EOBI & PESSI Laws', 'Payroll Withholding', 'Talent Retention', 'Provident Fund'],
  },
  {
    id: 'emp-4',
    employeeId: 'NEX-004',
    firstName: 'Bilal',
    lastName: 'Ahmed',
    email: 'bilal.fin@nexora.pk',
    phone: '+92 303 8291004',
    avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&q=80&w=200',
    department: 'Finance & FBR Tax Compliance',
    jobTitle: 'Chief Financial Officer (FCA / ICAP)',
    role: 'Finance Manager',
    manager: 'Muhammad Hamza Khan',
    branch: 'Karachi Corporate Head Office',
    joiningDate: '2020-06-15',
    status: 'Active',
    basicSalary: 550000,
    bankName: 'MCB Bank Ltd',
    accountNumber: 'PK12MUCB00445566778899',
    emergencyContact: { name: 'Nadia Ahmed', relationship: 'Spouse', phone: '+92 300 2233445' },
    skills: ['FBR Income Tax Ordinance', 'Sales Tax Annex-C', 'Withholding Audit', 'Treasury'],
  },
  {
    id: 'emp-5',
    employeeId: 'NEX-005',
    firstName: 'Zain Ul',
    lastName: 'Abideen',
    email: 'zain.tech@nexora.pk',
    phone: '+92 304 8291005',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    department: 'Software Engineering & IT',
    jobTitle: 'VP of Technology & Cloud Infrastructure',
    role: 'Department Manager',
    manager: 'Ayesha Siddiqui',
    branch: 'Lahore Tech & Operations Hub',
    joiningDate: '2021-04-01',
    status: 'Active',
    basicSalary: 480000,
    bankName: 'Meezan Bank Ltd',
    accountNumber: 'PK76MEZN00889911223344',
    emergencyContact: { name: 'Usman Abideen', relationship: 'Brother', phone: '+92 322 1199002' },
    skills: ['High-Availability Architecture', 'DevOps', 'Data Sovereignty', 'Security'],
  },
  {
    id: 'emp-6',
    employeeId: 'NEX-012',
    firstName: 'Saad',
    lastName: 'Farooq',
    email: 'saad.dev@nexora.pk',
    phone: '+92 305 8291012',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200',
    department: 'Software Engineering & IT',
    jobTitle: 'Senior Full Stack Engineer',
    role: 'Employee',
    manager: 'Zain Ul Abideen',
    branch: 'Karachi Corporate Head Office',
    joiningDate: '2022-08-15',
    status: 'Active',
    basicSalary: 280000,
    bankName: 'Habib Bank Limited (HBL)',
    accountNumber: 'PK99HABB00778899001122',
    emergencyContact: { name: 'Farooq Azam', relationship: 'Father', phone: '+92 312 8877665' },
    skills: ['Next.js', 'React', 'Node.js', 'FBR Iris API', 'PostgreSQL'],
  },
  {
    id: 'emp-7',
    employeeId: 'NEX-007',
    firstName: 'Sana',
    lastName: 'Mir',
    email: 'sana.sales@nexora.pk',
    phone: '+92 307 8291007',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=200',
    department: 'Corporate Sales & BD',
    jobTitle: 'Director of Enterprise B2B Sales',
    role: 'Sales Manager',
    manager: 'Ayesha Siddiqui',
    branch: 'Karachi Corporate Head Office',
    joiningDate: '2021-09-01',
    status: 'Active',
    basicSalary: 350000,
    bankName: 'Bank Alfalah Ltd',
    accountNumber: 'PK33ALFH00554433221100',
    emergencyContact: { name: 'Mir Alam', relationship: 'Father', phone: '+92 300 9988776' },
    skills: ['Corporate B2B Sales', 'Textile & Retail ERP', 'Client Retention'],
  },
  {
    id: 'emp-8',
    employeeId: 'NEX-010',
    firstName: 'Tariq',
    lastName: 'Mahmood',
    email: 'tariq.inv@nexora.pk',
    phone: '+92 308 8291010',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    department: 'Supply Chain & Multi-Godown',
    jobTitle: 'General Manager Warehousing & Godowns',
    role: 'Inventory Manager',
    manager: 'Ayesha Siddiqui',
    branch: 'Karachi Corporate Head Office',
    joiningDate: '2021-11-15',
    status: 'Active',
    basicSalary: 320000,
    bankName: 'Meezan Bank Ltd',
    accountNumber: 'PK88MEZN00112233445566',
    emergencyContact: { name: 'Samina Tariq', relationship: 'Spouse', phone: '+92 331 2233441' },
    skills: ['Godown Auditing', 'Port Logistics', 'Customs Clearance', 'Stock Reorder'],
  },
];

export const initialAttendance: AttendanceRecord[] = [
  {
    id: 'att-1',
    employeeId: 'NEX-001',
    employeeName: 'Muhammad Hamza Khan',
    department: 'Executive & Governance',
    date: '2026-10-06',
    clockIn: '08:45 AM',
    clockOut: '05:45 PM',
    breakDurationMinutes: 60,
    workingHours: 8.0,
    overtimeHours: 0.0,
    status: 'Present',
    approved: true,
  },
  {
    id: 'att-2',
    employeeId: 'NEX-002',
    employeeName: 'Ayesha Siddiqui',
    department: 'Executive & Governance',
    date: '2026-10-06',
    clockIn: '08:50 AM',
    clockOut: '06:15 PM',
    breakDurationMinutes: 45,
    workingHours: 8.5,
    overtimeHours: 0.5,
    status: 'Present',
    approved: true,
  },
  {
    id: 'att-3',
    employeeId: 'NEX-003',
    employeeName: 'Fatima Tariq',
    department: 'Human Resources & EOBI',
    date: '2026-10-06',
    clockIn: '08:55 AM',
    clockOut: '05:15 PM',
    breakDurationMinutes: 60,
    workingHours: 7.3,
    overtimeHours: 0,
    status: 'Present',
    approved: true,
  },
  {
    id: 'att-4',
    employeeId: 'NEX-012',
    employeeName: 'Saad Farooq',
    department: 'Software Engineering & IT',
    date: '2026-10-06',
    clockIn: '09:20 AM',
    breakDurationMinutes: 0,
    workingHours: 7.6,
    overtimeHours: 0,
    status: 'Late',
    approved: false,
  },
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: 'lve-1',
    employeeId: 'NEX-012',
    employeeName: 'Saad Farooq',
    department: 'Software Engineering & IT',
    leaveType: 'Annual Leave',
    startDate: '2026-10-20',
    endDate: '2026-10-24',
    days: 5,
    reason: 'Family visit to Abbottabad & Northern Areas.',
    status: 'Pending',
    appliedOn: '2026-10-04',
  },
  {
    id: 'lve-2',
    employeeId: 'NEX-003',
    employeeName: 'Fatima Tariq',
    department: 'Human Resources & EOBI',
    leaveType: 'Sick Leave',
    startDate: '2026-09-14',
    endDate: '2026-09-15',
    days: 2,
    reason: 'Medical recovery at Aga Khan University Hospital.',
    status: 'Approved',
    appliedOn: '2026-09-12',
    approvedBy: 'Muhammad Hamza Khan',
  },
];

export const initialPayslips: Payslip[] = [
  {
    id: 'pay-1',
    payslipNo: 'PAY-2026-09-001',
    employeeId: 'NEX-001',
    employeeName: 'Muhammad Hamza Khan',
    department: 'Executive & Governance',
    jobTitle: 'Managing Director & CEO',
    month: 'September',
    year: 2026,
    basicSalary: 650000,
    allowances: 95000,
    bonus: 100000,
    overtime: 0,
    grossSalary: 845000,
    taxDeduction: 185000,
    socialInsurance: 1000, // EOBI nominal deduction
    otherDeductions: 0,
    netSalary: 659000,
    status: 'Paid',
    paymentDate: '2026-09-30',
    paymentMethod: 'Raast / 1Link Bank Transfer',
  },
  {
    id: 'pay-2',
    payslipNo: 'PAY-2026-09-002',
    employeeId: 'NEX-003',
    employeeName: 'Fatima Tariq',
    department: 'Human Resources & EOBI',
    jobTitle: 'Head of People & EOBI Compliance',
    month: 'September',
    year: 2026,
    basicSalary: 380000,
    allowances: 45000,
    bonus: 25000,
    overtime: 0,
    grossSalary: 450000,
    taxDeduction: 68000,
    socialInsurance: 1000,
    otherDeductions: 0,
    netSalary: 381000,
    status: 'Paid',
    paymentDate: '2026-09-30',
    paymentMethod: 'Direct Deposit (Bank Alfalah)',
  },
  {
    id: 'pay-3',
    payslipNo: 'PAY-2026-09-003',
    employeeId: 'NEX-012',
    employeeName: 'Saad Farooq',
    department: 'Software Engineering & IT',
    jobTitle: 'Senior Full Stack Engineer',
    month: 'September',
    year: 2026,
    basicSalary: 280000,
    allowances: 35000,
    bonus: 20000,
    overtime: 15000,
    grossSalary: 350000,
    taxDeduction: 42000,
    socialInsurance: 1000,
    otherDeductions: 0,
    netSalary: 307000,
    status: 'Approved',
    paymentDate: '2026-09-30',
    paymentMethod: 'Direct Deposit (HBL)',
  },
];

export const initialJobOpenings: JobOpening[] = [
  {
    id: 'job-1',
    title: 'Lead ERP Systems Consultant (FBR Certified)',
    department: 'Software Engineering & IT',
    type: 'Full-time',
    positions: 2,
    experienceLevel: 'Senior (5+ yrs)',
    status: 'Active',
    postedDate: '2026-09-20',
    applicationsCount: 24,
  },
  {
    id: 'job-2',
    title: 'Enterprise Corporate Sales Lead',
    department: 'Corporate Sales & BD',
    type: 'Full-time',
    positions: 3,
    experienceLevel: 'Mid-Senior (4+ yrs)',
    status: 'Active',
    postedDate: '2026-09-25',
    applicationsCount: 31,
  },
];

export const initialCandidates: Candidate[] = [
  {
    id: 'cand-1',
    jobId: 'job-1',
    jobTitle: 'Lead ERP Systems Consultant',
    name: 'Omer Farooq Qureshi',
    email: 'omer.qureshi@gmail.com',
    phone: '+92 333 4411992',
    stage: 'Interview',
    score: 94,
    appliedDate: '2026-09-22',
    notes: 'In-depth experience in FBR Iris digital POS integrations for retail and textile chains.',
  },
  {
    id: 'cand-2',
    jobId: 'job-2',
    jobTitle: 'Enterprise Corporate Sales Lead',
    name: 'Mahnoor Baloch',
    email: 'mahnoor.baloch@outlook.com',
    phone: '+92 300 7788112',
    stage: 'Offer',
    score: 96,
    appliedDate: '2026-09-28',
    notes: 'Top performing SaaS enterprise sales track record; offer extended.',
  },
];

export const initialPerformanceReviews: PerformanceReview[] = [
  {
    id: 'rev-1',
    employeeId: 'NEX-012',
    employeeName: 'Saad Farooq',
    department: 'Software Engineering & IT',
    period: 'Q1 FY 2026-27',
    score: 4.8,
    goalsMetPercent: 98,
    strengths: 'Built lightning-fast FBR tax reporting and sales tax invoice generators with zero downtime.',
    improvements: 'Conduct more architectural handoffs with the junior engineering team in Lahore.',
    status: 'Completed',
    reviewedBy: 'Zain Ul Abideen',
    date: '2026-09-30',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Mian Shahid Mansha',
    companyName: 'Sapphire Textile Mills Ltd',
    email: 'accounts@sapphire.com.pk',
    phone: '+92 (42) 3571-2299',
    address: 'Gulberg Industrial Area, Lahore, Pakistan',
    status: 'Active',
    totalRevenue: 8500000,
    outstandingBalance: 650000,
    assignedTo: 'Sana Mir',
    createdAt: '2024-03-15',
  },
  {
    id: 'cust-2',
    name: 'Asif Peer',
    companyName: 'Systems Global Technologies',
    email: 'finance@systemsltd.com.pk',
    phone: '+92 (42) 3588-8800',
    address: 'Software Technology Park, Ferozepur Road, Lahore',
    status: 'Active',
    totalRevenue: 14200000,
    outstandingBalance: 0,
    assignedTo: 'Sana Mir',
    createdAt: '2023-11-20',
  },
  {
    id: 'cust-3',
    name: 'Ali Tabba',
    companyName: 'Lucky Core Distribution (Pvt) Ltd',
    email: 'orders@luckycore.com.pk',
    phone: '+92 (21) 3788-9900',
    address: 'Korangi Industrial Zone, Karachi, Pakistan',
    status: 'Active',
    totalRevenue: 6800000,
    outstandingBalance: 980000,
    assignedTo: 'Sana Mir',
    createdAt: '2024-08-10',
  },
];

export const initialLeads: Lead[] = [
  {
    id: 'lead-1',
    title: 'Textile Factory ERP & Inventory Automation',
    contactName: 'Khurram Mukhtar',
    company: 'Sadaqat Textiles Faisalabad',
    email: 'kmukhtar@sadaqatgroup.pk',
    phone: '+92 300 8661122',
    stage: 'Proposal',
    value: 4500000,
    probability: 80,
    assignedTo: 'Sana Mir',
    expectedCloseDate: '2026-11-15',
  },
  {
    id: 'lead-2',
    title: 'Retail Chain Multi-Store POS & FBR Integration',
    contactName: 'Naveed Asghar',
    company: 'Al-Fatah Departmental Stores',
    email: 'tech@alfatah.pk',
    phone: '+92 321 8442211',
    stage: 'Negotiation',
    value: 6200000,
    probability: 90,
    assignedTo: 'Sana Mir',
    expectedCloseDate: '2026-10-31',
  },
];

export const initialQuotations: Quotation[] = [
  {
    id: 'quot-1',
    quotationNumber: 'QT-2026-0081',
    customerId: 'cust-1',
    customerName: 'Sapphire Textile Mills Ltd',
    date: '2026-10-01',
    expiryDate: '2026-10-31',
    items: [
      { productId: 'prod-1', description: 'Nexora Enterprise Cloud ERP License (Annual)', quantity: 1, unitPrice: 2200000, total: 2200000 },
      { productId: 'prod-3', description: 'FBR Iris POS Integration & Data Migration', quantity: 1, unitPrice: 650000, total: 650000 },
    ],
    subtotal: 2850000,
    tax: 484500, // 17% Sales Tax in Pakistan
    discount: 100000,
    total: 3234500,
    status: 'Sent',
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'INV-PK-2026-0041',
    customerId: 'cust-1',
    customerName: 'Sapphire Textile Mills Ltd',
    issueDate: '2026-09-10',
    dueDate: '2026-10-10',
    items: [
      { description: 'Nexora Cloud ERP SaaS Quarterly Subscription', quantity: 1, unitPrice: 1500000, total: 1500000 },
      { description: 'Dedicated SLA Support & 1Link Payment Gateway', quantity: 1, unitPrice: 250000, total: 250000 },
    ],
    subtotal: 1750000,
    tax: 297500, // 17% Provincial / FBR Sales Tax
    discount: 50000,
    total: 1997500,
    amountPaid: 1347500,
    balanceDue: 650000,
    status: 'Partial',
  },
  {
    id: 'inv-2',
    invoiceNumber: 'INV-PK-2026-0042',
    customerId: 'cust-2',
    customerName: 'Systems Global Technologies',
    issueDate: '2026-09-01',
    dueDate: '2026-09-30',
    items: [
      { description: 'Annual Multi-Branch Multi-Currency License', quantity: 1, unitPrice: 3800000, total: 3800000 },
    ],
    subtotal: 3800000,
    tax: 646000,
    discount: 150000,
    total: 4296000,
    amountPaid: 4296000,
    balanceDue: 0,
    status: 'Paid',
  },
];

export const initialWarehouses: Warehouse[] = [
  { id: 'wh-1', name: 'Port Qasim Central Godown', code: 'PQ-KHI-01', location: 'Port Qasim Industrial Zone, Karachi', manager: 'Tariq Mahmood', capacity: 25000, currentStockUnits: 18400 },
  { id: 'wh-2', name: 'Sundar Industrial Logistics Hub', code: 'SIE-LHE-02', location: 'Sundar Industrial Estate, Lahore', manager: 'Rashid Minhas', capacity: 30000, currentStockUnits: 22100 },
  { id: 'wh-3', name: 'Rawat Dry Port Facility', code: 'RWT-ISB-03', location: 'G.T. Road, Rawat, Islamabad', manager: 'Kamran Akmal', capacity: 15000, currentStockUnits: 8900 },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    sku: 'NEX-SRV-01',
    barcode: '793573100124',
    name: 'Dell PowerEdge R750 Enterprise Server Unit',
    category: 'Hardware & Infrastructure',
    costPrice: 850000,
    sellingPrice: 1150000,
    stock: 22,
    minStockLevel: 5,
    warehouseId: 'wh-1',
    warehouseName: 'Port Qasim Central Godown',
    unit: 'Units',
  },
  {
    id: 'prod-2',
    sku: 'NEX-POS-02',
    barcode: '793573100254',
    name: 'Sunmi FBR-Approved Fiscal POS Terminal with Thermal Printer',
    category: 'Retail POS Hardware',
    costPrice: 95000,
    sellingPrice: 135000,
    stock: 65,
    minStockLevel: 15,
    warehouseId: 'wh-1',
    warehouseName: 'Port Qasim Central Godown',
    unit: 'Units',
  },
  {
    id: 'prod-3',
    sku: 'NEX-LIC-03',
    barcode: '793573100391',
    name: 'Nexora ERP Core Perpetual Enterprise License (FBR Integrated)',
    category: 'Software & Licenses',
    costPrice: 400000,
    sellingPrice: 1200000,
    stock: 150,
    minStockLevel: 20,
    warehouseId: 'wh-2',
    warehouseName: 'Sundar Industrial Logistics Hub',
    unit: 'Licenses',
  },
  {
    id: 'prod-4',
    sku: 'NEX-LAP-04',
    barcode: '793573100415',
    name: 'Lenovo ThinkPad T14 Gen 4 Core i7 32GB RAM',
    category: 'Workstations',
    costPrice: 380000,
    sellingPrice: 450000,
    stock: 18,
    minStockLevel: 8,
    warehouseId: 'wh-1',
    warehouseName: 'Port Qasim Central Godown',
    unit: 'Units',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Packages Limited',
    contactPerson: 'Kashif Mehmood',
    email: 'orders@packages.com.pk',
    phone: '+92 (42) 3581-1541',
    address: 'Walton Road, Lahore, Pakistan',
    categories: ['Packaging', 'Logistics Supplies'],
    status: 'Active',
  },
  {
    id: 'sup-2',
    name: 'National IT Hardware Distribution (Pvt) Ltd',
    contactPerson: 'Zubair Alam',
    email: 'sales@nationalit.pk',
    phone: '+92 (21) 3241-8899',
    address: 'Techno City Mall, I.I. Chundrigar Road, Karachi',
    categories: ['Servers', 'POS Terminals', 'Networking'],
    status: 'Active',
  },
];

export const initialPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-1',
    poNumber: 'PO-PK-2026-019',
    supplierId: 'sup-2',
    supplierName: 'National IT Hardware Distribution (Pvt) Ltd',
    orderDate: '2026-09-24',
    expectedDate: '2026-10-14',
    items: [
      {
        productId: 'prod-1',
        description: 'Dell PowerEdge R750 Enterprise Server Unit',
        quantity: 3,
        unitPrice: 850000,
        taxPercent: 17,
        taxAmount: 433500,
        total: 2983500,
      },
      {
        productId: 'prod-2',
        description: 'Sunmi FBR Fiscal POS Terminal with Thermal Printer',
        quantity: 8,
        unitPrice: 95000,
        taxPercent: 17,
        taxAmount: 129200,
        total: 889200,
      },
    ],
    subtotal: 3310000,
    tax: 562700,
    totalAmount: 3872700,
    deliveryAddress: 'Port Qasim Central Godown, Karachi',
    paymentTerms: '30 Days Net via 1Link Corporate Wire',
    notes: 'Urgent delivery for Q4 system expansion',
    status: 'Approved',
  },
];

export const initialVisitorSessions: VisitorSession[] = [
  {
    id: 'vis-uae-1',
    ipAddress: '2.51.136.167',
    city: 'Dubai',
    province: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    flag: '🇦🇪',
    isp: 'du / Emirates Integrated Telecommunications',
    device: 'Executive Workstation',
    browser: 'Chrome 130.0',
    os: 'Windows 11 Pro',
    activePage: '/dashboard',
    referrer: 'Direct / Dubai Regional HQ',
    duration: '22 mins',
    status: 'Active Now',
    timestamp: 'Today, 12:05 PM',
  },
  {
    id: 'vis-1',
    ipAddress: '119.160.118.22',
    city: 'Karachi',
    province: 'Sindh',
    country: 'Pakistan',
    countryCode: 'PK',
    flag: '🇵🇰',
    isp: 'PTCL Fiber Broadband',
    device: 'Desktop Workstation',
    browser: 'Chrome 129.0',
    os: 'Windows 11 Enterprise',
    activePage: '/sales/invoices',
    referrer: 'Direct / Intranet',
    duration: '18 mins',
    status: 'Active Now',
    timestamp: 'Today, 11:14 AM',
  },
  {
    id: 'vis-2',
    ipAddress: '39.40.12.89',
    city: 'Lahore',
    province: 'Punjab',
    country: 'Pakistan',
    countryCode: 'PK',
    flag: '🇵🇰',
    isp: 'Nayatel Gigabit Fiber',
    device: 'MacBook Pro 16"',
    browser: 'Safari 18.0',
    os: 'macOS Sonoma',
    activePage: '/reports/marketing',
    referrer: 'https://google.com',
    duration: '9 mins',
    status: 'Active Now',
    timestamp: 'Today, 11:22 AM',
  },
  {
    id: 'vis-ksa-1',
    ipAddress: '212.118.142.15',
    city: 'Riyadh',
    province: 'Riyadh Province',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    flag: '🇸🇦',
    isp: 'STC Telecom KSA',
    device: 'ThinkPad X1 Carbon',
    browser: 'Edge 130.0',
    os: 'Windows 11',
    activePage: '/inventory/warehouses',
    referrer: 'GCC Partner Portal',
    duration: '14 mins',
    status: 'Active Now',
    timestamp: 'Today, 11:40 AM',
  },
  {
    id: 'vis-uk-1',
    ipAddress: '86.14.92.110',
    city: 'London',
    province: 'Greater London',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    isp: 'British Telecom',
    device: 'MacBook Air M3',
    browser: 'Safari 18.1',
    os: 'macOS Sequoia',
    activePage: '/crm/customers',
    referrer: 'Overseas Investor Portal',
    duration: '31 mins',
    status: 'Idle',
    timestamp: 'Today, 10:50 AM',
  },
  {
    id: 'vis-3',
    ipAddress: '182.180.144.10',
    city: 'Islamabad',
    province: 'Federal Capital',
    country: 'Pakistan',
    countryCode: 'PK',
    flag: '🇵🇰',
    isp: 'StormFiber Enterprise',
    device: 'Desktop PC',
    browser: 'Edge 129.0',
    os: 'Windows 10 Pro',
    activePage: '/inventory/products',
    referrer: 'https://linkedin.com',
    duration: '26 mins',
    status: 'Idle',
    timestamp: 'Today, 10:55 AM',
  },
  {
    id: 'vis-4',
    ipAddress: '111.88.24.55',
    city: 'Faisalabad',
    province: 'Punjab',
    country: 'Pakistan',
    countryCode: 'PK',
    flag: '🇵🇰',
    isp: 'Jazz 4G LTE Data',
    device: 'Samsung Galaxy S24 Ultra',
    browser: 'Chrome Mobile',
    os: 'Android 14',
    activePage: '/hr/payroll',
    referrer: 'Direct / Bookmark',
    duration: '5 mins',
    status: 'Active Now',
    timestamp: 'Today, 11:25 AM',
  },
  {
    id: 'vis-5',
    ipAddress: '202.163.112.4',
    city: 'Rawalpindi',
    province: 'Punjab',
    country: 'Pakistan',
    countryCode: 'PK',
    flag: '🇵🇰',
    isp: 'Transworld Home Fiber',
    device: 'Apple iPad Pro',
    browser: 'Safari Mobile',
    os: 'iPadOS 18.0',
    activePage: '/reports',
    referrer: 'Email Digest Link',
    duration: '34 mins',
    status: 'Left',
    timestamp: 'Today, 10:15 AM',
  },
];


export const initialExpenseClaims: ExpenseClaim[] = [
  {
    id: 'exp-1',
    claimNumber: 'EXP-PK-2026-081',
    employeeId: 'NEX-007',
    employeeName: 'Sana Mir',
    department: 'Corporate Sales & BD',
    category: 'Client Dinner & Entertainment',
    amount: 38500,
    date: '2026-10-02',
    description: 'Corporate dinner with Sapphire Textiles Board at Pearl Continental Lahore.',
    receiptName: 'pc-lahore-receipt.pdf',
    status: 'Approved',
    approvedBy: 'Bilal Ahmed',
  },
  {
    id: 'exp-2',
    claimNumber: 'EXP-PK-2026-082',
    employeeId: 'NEX-012',
    employeeName: 'Saad Farooq',
    department: 'Software Engineering & IT',
    category: 'Travel & Accommodation',
    amount: 45000,
    date: '2026-10-03',
    description: 'Serena Islamabad hotel stay for FBR Iris API technical sync meeting.',
    receiptName: 'serena-isb-invoice.pdf',
    status: 'Approved',
    approvedBy: 'Bilal Ahmed',
  },
];

export const initialAccounts: Account[] = [
  { id: 'acc-1', code: '1010', name: 'Petty Cash - Karachi Head Office', type: 'Asset', balance: 250000, currency: 'PKR' },
  { id: 'acc-2', code: '1020', name: 'Meezan Bank Operating Account', type: 'Asset', balance: 48500000, currency: 'PKR' },
  { id: 'acc-3', code: '1030', name: 'Habib Bank Limited (HBL) Payroll Account', type: 'Asset', balance: 18200000, currency: 'PKR' },
  { id: 'acc-4', code: '1200', name: 'Accounts Receivable (Debtors)', type: 'Asset', balance: 1630000, currency: 'PKR' },
  { id: 'acc-5', code: '2010', name: 'Accounts Payable (Creditors)', type: 'Liability', balance: 2450000, currency: 'PKR' },
  { id: 'acc-6', code: '2040', name: 'FBR Sales Tax Payable (17%)', type: 'Liability', balance: 1840000, currency: 'PKR' },
  { id: 'acc-7', code: '2050', name: 'Accrued EOBI & Social Security', type: 'Liability', balance: 350000, currency: 'PKR' },
  { id: 'acc-8', code: '3010', name: 'Paid Up Capital & Retained Earnings', type: 'Equity', balance: 45000000, currency: 'PKR' },
  { id: 'acc-9', code: '4010', name: 'Enterprise Cloud ERP SaaS Revenue', type: 'Revenue', balance: 82500000, currency: 'PKR' },
  { id: 'acc-10', code: '5010', name: 'Staff Salaries, EOBI & Benefits', type: 'Expense', balance: 32400000, currency: 'PKR' },
];

export const initialProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'FBR Digital Invoicing & SRO Compliance Engine',
    code: 'PRJ-FBR-01',
    manager: 'Zain Ul Abideen',
    department: 'Software Engineering & IT',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    budget: 8500000,
    spent: 4900000,
    progressPercent: 78,
    status: 'Active',
    priority: 'High',
  },
  {
    id: 'proj-2',
    name: 'Sapphire Textiles Nationwide ERP Rollout',
    code: 'PRJ-SPH-02',
    manager: 'Ayesha Siddiqui',
    department: 'Executive & Governance',
    startDate: '2026-09-01',
    endDate: '2027-02-28',
    budget: 12000000,
    spent: 4200000,
    progressPercent: 42,
    status: 'Active',
    priority: 'High',
  },
  {
    id: 'proj-3',
    name: 'Raast & 1Link Real-Time Corporate Disbursals',
    code: 'PRJ-FIN-03',
    manager: 'Bilal Ahmed',
    department: 'Finance & FBR Tax Compliance',
    startDate: '2026-07-01',
    endDate: '2026-10-31',
    budget: 3500000,
    spent: 3100000,
    progressPercent: 92,
    status: 'Active',
    priority: 'High',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    projectName: 'FBR Digital Invoicing & SRO Compliance Engine',
    title: 'Validate FBR Iris JSON Payload with HMAC Signatures',
    description: 'Ensure automated digital invoices pass Federal Board of Revenue cryptographic validation.',
    assigneeId: 'NEX-012',
    assigneeName: 'Saad Farooq',
    priority: 'Urgent',
    status: 'In Progress',
    dueDate: '2026-10-15',
    commentsCount: 5,
  },
  {
    id: 'task-2',
    projectId: 'proj-3',
    projectName: 'Raast & 1Link Real-Time Corporate Disbursals',
    title: 'Verify Raast IBAN direct salary credit endpoint',
    description: 'Test batch dispatches to Meezan, HBL, and Alfalah accounts.',
    assigneeId: 'NEX-012',
    assigneeName: 'Saad Farooq',
    priority: 'High',
    status: 'Review',
    dueDate: '2026-10-12',
    commentsCount: 3,
  },
];

export const initialDocuments: DocumentRecord[] = [
  { id: 'doc-1', title: 'Nexora Code of Conduct & Pakistan Labor Laws 2026.pdf', category: 'Policies', fileType: 'PDF', fileSize: '2.8 MB', uploadedBy: 'Fatima Tariq', uploadDate: '2026-01-10', version: 'v3.2' },
  { id: 'doc-2', title: 'SECP Incorporation Certificate & Form 29.pdf', category: 'Contracts', fileType: 'PDF', fileSize: '1.4 MB', uploadedBy: 'Muhammad Hamza Khan', uploadDate: '2026-02-15', version: 'v1.0' },
  { id: 'doc-3', title: 'FBR Sales Tax & NTN Registration Certificate.pdf', category: 'Finance', fileType: 'PDF', fileSize: '1.1 MB', uploadedBy: 'Bilal Ahmed', uploadDate: '2026-03-01', version: 'v1.0' },
  { id: 'doc-4', title: 'Sapphire Textiles Master Services Agreement.pdf', category: 'Contracts', fileType: 'PDF', fileSize: '4.2 MB', uploadedBy: 'Sana Mir', uploadDate: '2026-04-10', version: 'v1.2' },
];

export const initialCalendarEvents: CalendarEvent[] = [
  { id: 'cal-1', title: 'Quarterly Executive Review & Board Sync', type: 'Meeting', date: '2026-10-08', startTime: '10:00 AM', endTime: '12:00 PM', location: 'Dolmen Executive Boardroom / Zoom', participants: ['Muhammad Hamza Khan', 'Ayesha Siddiqui', 'Bilal Ahmed'] },
  { id: 'cal-2', title: 'FBR Tax Withholding & Annex-C Audit', type: 'Meeting', date: '2026-10-14', startTime: '02:30 PM', endTime: '04:00 PM', location: 'Finance Suite, Karachi', participants: ['Bilal Ahmed', 'Mariam Baig'] },
  { id: 'cal-3', title: 'Iqbal Day Public Holiday', type: 'Holiday', date: '2026-11-09', startTime: 'All Day', endTime: 'All Day', location: 'Nationwide Pakistan', participants: ['All Staff'] },
  { id: 'cal-4', title: 'Quaid-e-Azam Day & National Holiday', type: 'Holiday', date: '2026-12-25', startTime: 'All Day', endTime: 'All Day', location: 'Nationwide Pakistan', participants: ['All Staff'] },
];

export const initialAssets: Asset[] = [
  { id: 'ast-1', assetTag: 'NEX-AST-001', name: 'Dell PowerEdge R750 Enterprise Server', category: 'Computers', serialNumber: 'SRV-882910-PK', purchaseDate: '2024-02-15', cost: 1150000, assignedTo: 'Zain Ul Abideen', department: 'Software Engineering & IT', status: 'In Use' },
  { id: 'ast-2', assetTag: 'NEX-AST-002', name: 'Toyota Hilux Revo Corporate Logistics Fleet', category: 'Vehicles', serialNumber: 'VIN-KHI-88910', purchaseDate: '2023-08-20', cost: 11800000, assignedTo: 'Tariq Mahmood', department: 'Supply Chain & Multi-Godown', status: 'In Use' },
  { id: 'ast-3', assetTag: 'NEX-AST-003', name: 'MacBook Pro 16" M3 Max 36GB RAM', category: 'Computers', serialNumber: 'MBP-2024-9912', purchaseDate: '2024-04-10', cost: 890000, assignedTo: 'Saad Farooq', department: 'Software Engineering & IT', status: 'In Use' },
];

export const initialTickets: Ticket[] = [
  { id: 'tkt-1', ticketNumber: 'TKT-PK-1042', subject: 'FBR Iris API sandbox test key renewed', category: 'IT Support', requesterName: 'Saad Farooq', assignedTo: 'IT Support Desk', priority: 'High', status: 'In Progress', createdAt: '2026-10-06 09:12' },
  { id: 'tkt-2', ticketNumber: 'TKT-PK-1043', subject: 'Meezan Bank Raast Corporate IBAN update', category: 'HR Inquiry', requesterName: 'Fatima Tariq', assignedTo: 'Bilal Ahmed', priority: 'Medium', status: 'Open', createdAt: '2026-10-05 14:30' },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Nexora Recognized as Top Enterprise ERP Solution in Pakistan for FY 2026',
    content: 'We are proud to share that Nexora has crossed 120+ enterprise rollouts across Karachi, Lahore, Faisalabad, and Islamabad! Thank you to our stellar engineering, sales, and operations teams.',
    author: 'Muhammad Hamza Khan (CEO)',
    date: '2026-10-05',
    priority: 'Urgent',
    department: 'All',
  },
  {
    id: 'ann-2',
    title: 'Jummah Prayer Hours & Friday Working Schedule Reminder',
    content: 'Please note Friday Jummah prayer break from 1:00 PM to 2:30 PM across all Karachi, Lahore, and Islamabad offices. All afternoon client syncs should be scheduled accordingly.',
    author: 'Fatima Tariq (Head of HR)',
    date: '2026-10-04',
    priority: 'High',
    department: 'All',
  },
];

export const initialNotifications: NotificationItem[] = [
  { id: 'notif-1', title: 'New Leave Request', message: 'Saad Farooq submitted an Annual Leave request for Oct 20-24.', type: 'info', timestamp: '10 mins ago', read: false, link: '/hr/leave' },
  { id: 'notif-2', title: 'FBR Annex-C Filing Due', message: 'Monthly Sales Tax Return Annexure C submission due in 5 days.', type: 'warning', timestamp: '1 hour ago', read: false, link: '/sales/invoices' },
  { id: 'notif-3', title: 'Low Stock Alert - Port Qasim Godown', message: 'Sunmi FBR POS terminals down to 15 units (Threshold: 20).', type: 'error', timestamp: '3 hours ago', read: false, link: '/inventory/products' },
];

export const initialAuditLogs: AuditLog[] = [
  { id: 'aud-1', userId: 'usr-1', userName: 'Muhammad Hamza Khan', action: 'Approved Leave Request', module: 'leave', details: 'Approved Sick Leave for Fatima Tariq (NEX-003)', ipAddress: '119.160.118.22', timestamp: '2026-09-12 10:14 AM' },
  { id: 'aud-2', userId: 'usr-4', userName: 'Bilal Ahmed', action: 'Created Invoice', module: 'sales', details: 'Generated FBR Sales Tax INV-PK-2026-0041 for Sapphire Textiles (Rs. 1,997,500)', ipAddress: '119.160.118.45', timestamp: '2026-09-10 03:22 PM' },
  { id: 'aud-3', userId: 'usr-1', userName: 'Muhammad Hamza Khan', action: 'System Login', module: 'dashboard', details: 'Successful 2FA Authenticated Login from Karachi HQ Fiber', ipAddress: '119.160.118.22', timestamp: '2026-10-06 08:30 AM' },
];
